### ISSUE TITLE
Only elytra in hotbar working (1.20.4)

### ISSUE THREAD

**Issue by jokesper** [NimajnebEC/auto-elytra#10]
Only elytra  in my hotbar or offhand are used for switching.
Any other inventory slot is ignored.

**Comment by brooke-ec** [comment]
Thanks for the bug report! :D

This seems to be caused by tightening restrictions on what slots [`ClickType.SWAP`](https://github.com/NimajnebEC/auto-elytra/blob/e341224ecb805e3d4602914742889adca058e563/common/src/main/java/net/nimajnebec/autoelytra/mixin/LocalPlayerMixin.java#L100) can be used with. This should be able to be avoided by using `ClickType.PICKUP` 3 times, mimicking normal client behavior...

**Comment by brooke-ec** [comment]
You should now be able to download the fixed version from [GitHub Releases](https://github.com/NimajnebEC/auto-elytra/releases/tag/v2.1.1-1.20.4) or [Modrinth](https://modrinth.com/mod/auto-elytra/version/2.1.1)!
