### ISSUE TITLE
Not Working on Paper server

### ISSUE THREAD

**Issue by papagajptica** [NimajnebEC/auto-elytra#7]
So this mod works fine in singleplayer and multiplayer vanilla servers, but when I join a Paper server it doesn't work. It switches the elytra and chestplate twice so the chestplate doesn't change

**Comment by stefansaraev** [comment]
fyi: same behaviour with 1.20.4 fabric build and spigot server. singleplayer is ok. so its not paper specific, but (newer) spigot/paper.

**Comment by brooke-ec** [comment]
Sorry for the delay! I wasn't able to recreate this issue in my testing but the mod was broken with 1.20.4, so its likely this was partially caused by that. Try updating and let me know if you continue to encounter problems!

You should now be able to download the 1.20.4 version from [GitHub Releases](https://github.com/NimajnebEC/auto-elytra/releases/tag/v2.1.0-1.20.4) or [Modrinth](https://modrinth.com/mod/auto-elytra/version/5frttax8)!

**Comment by stefansaraev** [comment]
thanks! we swiched our server to spigot due to other issues we had with paper., but latest 1.20.4 autoelytra fabric build works fine now.
